parse metric name and tags with histograms support
librato/statsd-librato-backend pull request #81
Opened 2017-04-21 00:09 UTC by mugurax

When sending timers with histograms, statsd creates new gauges with .bin_x added to the original metric name.

For instance: global-prefix.name#tag=val is sent to statsd-librato-backend as global-prefix.name#tag=val.bin_50

This format is not supported by the existing parseAndSetTags.

Thanks,
Mugur

2017-04-21 01:49 UTC, bryanmikaelian commented
Thanks for the report / fix + test! I'll check on this tomorrow morning (I'm CST)

2017-04-21 15:03 UTC, bryanmikaelian requested changes
Would it be possible to move your logic for parsing the `bin_` suffix out to here https://github.com/librato/statsd-librato-backend/blob/master/lib/librato.js#L377? I would prefer to keep `parseAndSetTags` focused on just parsing tags out and keep timer-specific logic contained inside here: https://github.com/librato/statsd-librato-backend/blob/master/lib/librato.js#L343

For timers and their suffixes (p99, etc), we handle similar logic with tags inside the function called here https://github.com/librato/statsd-librato-backend/blob/master/lib/librato.js#L365.

Other than that, looks great!

2017-04-21 15:04 UTC, bryanmikaelian commented
cc @jderrett

2017-04-21 15:53 UTC, bryanmikaelian requested changes

2017-04-21 15:53 UTC, bryanmikaelian commented on test/librato_tests.js
> +    let metrics = {gauges: {'my_gauge#foo=bar.bin_50': 1}};
This is a good test but we probably want to build a proper `timer` metric to fully test this code path: https://github.com/librato/statsd-librato-backend/blob/master/lib/librato.js#L373.

2017-04-21 16:50 UTC, mugurax commented
Regarding these commits: 

@mugurax	disabled debug override			94da786
@mugurax	disabled debug override			4dcd2d6

They were not intended to reach this pull request :( I am not sure how should I proceed. Sorry for the trouble.

2017-04-21 17:37 UTC, bryanmikaelian commented
@mugurax No worries! You can make the change on your branch and update the PR.

2017-05-05 19:27 UTC, bryanmikaelian commented
Any updates?

2018-08-20 19:10 UTC, johanneswuerbach commented
@bryanmikaelian any update here? I would happily take this over otherwise.

2018-08-21 15:54 UTC, bryanmikaelian commented
cc @mbeale . You ok with @johanneswuerbach taking this over? I can try to get it knocked out but no ETA. Is this something Librato still wants to support?

2018-08-22 17:38 UTC, mbeale commented
@bryanmikaelian probably ok for @johanneswuerbach to take over.  I'm not sure if Librato will release another version.

2025-03-28 15:06 UTC, closed without merging